
package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.*;
import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.commons.domain.Dish;
import co.unicauca.restaurant.client.domain.services.DishService;
import static co.unicauca.restaurant.client.infra.Messages.successMessage;
import co.unicauca.restaurant.client.access.IDishAccess;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 * Interfaz gráfica de Consultar clientes
 *
 * @author Libardo Pantoja
 *
 */
public class GUIDish extends javax.swing.JInternalFrame {

    /**
     * Constructor
     */
    public GUIDish() {
        initComponents();

        setSize(870, 500);
        fijarMensajeExplicacion();
        btnAgregar.setVisible(false);
    }

    /**
     * Mensaje inicial del panel superior
     */
    private void fijarMensajeExplicacion() {
        StringBuilder sb = new StringBuilder(64);
        sb.append("<html>" + "Este ejercicio aplica el patrón template method.<br>"
                + "La aplicación cliente se conecta al servidor mediante Sockets.<br>"
                + "El servidor devuelve el objeto Dish consultado en formato JSON.<br>"
                + "En el backend los idenficadores desde 2020001 hasta 2020005.<br>"
                + "</html>");
        lblExplicacion.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCentro = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        pnlSur = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        pnlNorte = new javax.swing.JPanel();
        lblExplicacion = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Clientes");

        pnlCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCentro.setLayout(new java.awt.GridLayout(4, 2));

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("*Nombre:");
        pnlCentro.add(lblNombre);
        pnlCentro.add(txtName);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("*Descripcion:");
        pnlCentro.add(jLabel1);
        pnlCentro.add(txtDescription);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("*Precio:");
        pnlCentro.add(jLabel2);
        pnlCentro.add(txtPrice);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("*Tamaño(ALL, HALF):");
        pnlCentro.add(jLabel3);
        pnlCentro.add(txtSize);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlSur.add(btnAgregar);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cerrar.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlSur.add(btnCerrar);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pnlNorte.setBorder(new javax.swing.border.MatteBorder(null));
        pnlNorte.setLayout(new java.awt.GridBagLayout());

        lblExplicacion.setText("lblExplicacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlNorte.add(lblExplicacion, gridBagConstraints);

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("Identificador del plato:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlNorte.add(lblId, gridBagConstraints);

        txtId.setText("2020001");
        txtId.setPreferredSize(new java.awt.Dimension(150, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlNorte.add(txtId, gridBagConstraints);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlNorte.add(btnBuscar, gridBagConstraints);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    public String getTxtyId() {
        return txtId.getText();
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String id = txtId.getText().trim();

        IDishAccess service = Factory.getInstance().getDishService();
        // Inyecta la dependencia
        DishService dishService = new DishService(service);
        if (id.equals("")) {
            btnAgregar.setVisible(false);
            txtName.requestFocus();
            return;
        }

        Dish dish;
        try {
            dish = dishService.findDish(id);
        } catch (Exception ex) {
            clearControls();
            successMessage(ex.getMessage(), "Atención");
            btnAgregar.setVisible(true);
            return;
        }
        clearControls();
        showData(dish);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        IDishAccess service = Factory.getInstance().getDishService();
        // Inyecta la dependencia
        DishService dishService = new DishService(service);

        Dish dish = new Dish();
        dish.setId(txtId.getText());
        dish.setName(txtName.getText());
        dish.setDescription(txtDescription.getText());
        dish.setPrice(txtPrice.getText());
        dish.setSize(txtSize.getText());

        try {
            String response = dishService.createDish(dish);
            successMessage("Plato " + response + " agregado con éxito.", "Atención");
            clearControls();
            txtId.setText("");
            btnAgregar.setVisible(false);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }


    }//GEN-LAST:event_btnAgregarActionPerformed
    /**
     * Muestra los datos en el formulario
     *
     * @param customer cliente
     */
    private void showData(Dish dish) {
        txtName.setText(dish.getName());
        txtDescription.setText(dish.getDescription());
        txtPrice.setText(dish.getPrice());
        txtSize.setText(dish.getSize());
    }

    public void clearControls() {
        txtName.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        txtSize.setText("");
    }

    public static void main(String[] args) {
        GUIDish gui = new GUIDish();
        gui.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblExplicacion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables

}
